let products = [
    {
        productname: " Spring Flower",
        image: "../Media/PRODUCTS/flower1.jpg",
        price: "480000",
        quantity: 1,
        detail: "Pink Gerbera brings a sense of warmth and joy to your special's one while it also arranges with mixed flowers , which create a feeling of celebration.  So, If you are finding a flower with vase for celebrating any special occasion, likes Birthday or anniversary. Our Pink Gerbera & Mixed Flowers with Vase would be a great choice. ",
        type: "gift",

    },
    {
        productname: "PINK GERBERA & MIXED FLOWERS WITH VASE",
        image: "../Media/PRODUCTS/flower2.jpg",
        price: "650000",
        quantity: 1,
        detail: "Pink Gerbera brings a sense of warmth and joy to your special's one while it also arranges with mixed flowers , which create a feeling of celebration.  So, If you are finding a flower with vase for celebrating any special occasion, likes Birthday or anniversary. Our Pink Gerbera & Mixed Flowers with Vase would be a great choice. ",
        type: "gift",
    },
    {
        productname: "LITTLE FLOWER BOUQUET",
        image: "../Media/PRODUCTS/flower3.webp",
        price: "650000",
        quantity: 1,
        detail: "Avibrant burst of stunning colours and fresh, floral aromas make this little flower bouquet the perfect gift for any occasion or simply for showing somebody special in your life just how much you care about them . A unique bouquet every time, the little flowers bouquet is sure to put a smile on anybodys face whether you are saying Happy Birthday to your mum or sending them to your wife to let her know how much you appreciate everything she does.Give them to a friend who needs a pick- me - up or just buy them for yourself to display in your home and add some colours.",
        type: "gift",
    },
    {
        productname: "TULIPS IN ROUND FLOWER BOX",
        image: "../Media/PRODUCTS/flower4.jpg",
        price: "1480000",
        quantity: 1,
        detail: "A symbol of simple love, charity, paradise on earth, heavenly and reminder of the passion of life. Send your warm love and regards with our sun-kissed tulips to captivate the admiration of your loved ones. This Flower Box includes: 18 - 20 stems of Season's Best Tulips (No Specific Color) and Standard Round Gift Box Dimensions: 16cm(H) x 13cm(W).  ",
        type: "gift",
    },
    {
        productname: "CLASSIC RED ROSE BOUQUET",
        image: "../Media/PRODUCTS/flower5.jpg",
        price: "990000",
        quantity: 1,
        detail: "Classic Red Rose Bouquet would be a delightful choice for celebrating any occasion, especially since the red rose is a classic symbol of love and passion. Our Classic Red Rose Bouquets are crafted and designed by professional florists and only fresh red roses are used in all bouquet. If you want to impress your recipients,  giving them a  Classic Red Rose Bouquet is a gesture that can't be missed. ",
        type: "gift",
    },
    {
        productname: "MINI HYDRANGEA BOUQUET",
        image: "../Media/PRODUCTS/flower6.webp",
        price: "480000",
        quantity: 1,
        detail: "The hydrangea is an ornate flower with unique, woody stems.The lacy nature of the flower means that the blooms are a special delight for the special person who receives them . Hydrangeas in every color, ranging from purple to pink are enchanting.Sending this bouquet of hydrangeas to somebody special sends the message of gratefulness and understanding in many cases, creating a heartfelt message . This flower is also commonly given as a wedding anniversary gift, making it a romantic choice ",
        type: "gift",
    },
    {
        productname: "Inside Scoop Ice Cream & Bouquet Set",
        image: "../Media/PRODUCTS/flower7.webp",
        price: "580000",
        quantity: 1,
        detail: "For those who love ice cream & flowers (who doesn't?). The Inside Scoop ice Cream & Bouquet Set contains your choice of one Inside Scoop ice cream pint and one BloomThis hand bouquet. Just the best thing to send to someone in need of some serious cheering up.",
        type: "gift",
    },
    {
        productname: "VIBRANT PINK MELODY",
        image: "../Media/PRODUCTS/flower8.jpg",
        price: "1880000",
        quantity: 1,
        detail: "Looking for flowers with a gorgeous hue and giving off a lively feeling? Why not try one with a combination of different pink flowers? This vibrant mix includes different shades of pink that symbolize femininity. The pink-colored bouquet oozes cheer, affection, and playfulness . Our skilled florists put together this bouquet to offer our customers value and quality.The flowers would look good not only in a bouquet but also in table centerpieces, wedding décor, and other celebratory events.",
        type: "gift",
    },
    {
        productname: "BLUE ROSE BOUQUET ",
        image: "../Media/PRODUCTS/flower9.webp",
        price: "33480000",
        quantity: 1,
        detail: "There's nothing better then gifting a elegant rose bouquet to celebrating any special occasion, Our Blue Rose Bouquet is the perfect gift to express your love and care for your special someone.  If you want to brighten someone's day,  a Blue Rose Bouquet would be a truly unique gift that creates  an unforgettable moment. ",
        type: "gift",
    },
    {
        productname: "MIXED TULIPS IN VASE",
        image: "../Media/PRODUCTS/flower10.webp",
        price: "1880000",
        quantity: 1,
        detail: "Tulips are a flower commonly associated with friendship and positivity. Tulips are among the most cheerful flowers available, so it only makes sense that our Mixed Tulips in Vase is such a popular option . Our stunning arrangement of 16 to 20 stems makes a gorgeous bouquet you can gift for any occasion, whether it is a birthday, holiday or congratulatory event.Plus, it comes in a beautiful glass vase.",
        type: "gift",
    },
    {
        productname: "YELLOW DELIGHT",
        image: "../Media/PRODUCTS/flower11.jpg",
        price: "3480000",
        quantity: 1,
        detail: "This delightful bouquet would make a great present for someone towards whom you want to express your love and respect. Yellow flowers carry that message so well. The recipient will beam with joy as s/he admires this cheery bouquet . The yellow and white flowers are skillfully wrapped in soft brown craft paper and tied with cream and pink ribbons.This fabulous arrangement is literally the best gift you can get for someone you want to feel loved and cared for.",
        type: "gift",
    },
    {
        productname: "PINKY LOLLY",
        image: "../Media/PRODUCTS/flower12.jpeg",
        price: "480000",
        quantity: 1,
        detail: "If you want to give a floral gift that really stands out from the crowd, this pinky lolly bouquet is the perfect choice. An elegant gift that won’t be forgotten in a while, this combination of the season’s best roses and spray roses will take pride of place in the home . The perfect gift for showing you care on an anniversary, Mother’s Day, Valentine’s Day, a birthday, or just because you want somebody special in your life to know that you love and appreciate them, this pinky lolly bouquet complete with a complimentary message card is sure to put a smile on anyone’s face.",
        type: "gift",
    },
    {
        productname: " VIBRANT GLAMOROUS FLOWER STAND",
        image: "../Media/PRODUCTS/flower12.jpg",
        price: "3480000",
        quantity: 1,
        detail: "The delicate pink, red, orange, and blue flowers come together harmoniously with the green foliage to create a blossoming masterpiece.",
        type: "congratulation",
    },
    {
        productname: " ELEGANT FLOWER STAND",
        image: "../Media/PRODUCTS/flower13.jpg",
        price: "2880000",
        quantity: 1,
        detail: "A flower stand can send a grand message, unveiling a lovely message of appreciation and congratulations. Send our standard or large Elegant Flower Stand to your friend’s grand opening or a corporate event . This luscious flower stand offers an abundance of seasonal flowers, including cabbages, roses and other matching flowers, all surrounded by seasonal greenery that makes those colors pop. Express your congratulations by adding a bottle of champagne too.",
        type: "congratulation",
    },
    {
        productname: "GRACEFUL GERBERAS & LILIES FLOWER STAND",
        image: "../Media/PRODUCTS/flower14.jpg",
        price: "3080000",
        quantity: 1,
        detail: "Flower stands can send meaningful messages to loved ones near and far, and the Graceful Gerberas & Lilies Flower Stand is no exception . This flower stand boasts pale pink gerberas matched with seasonal flowers in deep purple.Lilies are added to the flower stand as a lovely accent. All these flowers rest on a bed of green foliage for a forest green backdrop.",
        type: "congratulation",
    },
    {
        productname: "GLAMOROUS SUNFLOWER & GERBERAS FLOWER STAND",
        image: "../Media/PRODUCTS/flower15.jpg",
        price: "3080000",
        quantity: 1,
        detail: "Sunflowers and gerberas are both beautiful blooms with the power to light up an entire room .Gerberas are pleasant and bright, while sunflowers are warm and explosive.In this arrangement, the flowers rest on a bed of seasonal foliage.This stand is the perfect congratulatory gift with its cheerful flowers and delightful colors.",
        type: "congratulation",
    },
    {
        productname: "DELIGHTFUL FLOWER STAND",
        image: "../Media/PRODUCTS/flower16.jpg",
        price: "3080000",
        quantity: 1,
        detail: "Congratulate somebody you care about with our Delightful Flower Stand. Order this perfect gift with or without a stand, depending on your needs, and see the smiles emerge.Share a message of congratulations or wish a friend success with our beautiful arrangement of red ginger lilies, chrysanthemums and carnations, all surrounded by seasonal foliage.Add a bottle of Veuve Cliquot Yellow Label Champagne for some extra celebration.",
        type: "congratulation",
    },
    {
        productname: "CONGRATULATIONS FLOWER ARRANGEMENT",
        image: "../Media/PRODUCTS/flower17.png",
        price: "2880000",
        quantity: 1,
        detail: "Are you looking for a new way to express your congratulations to somebody you care about? Our Congratulations Flower Arrangement is stunning with its diversity of blooms, ranging from birds of paradise to gerberas. The assortment offers gorgeous dendrobium orchids and seasonal foliage, all on a large flower stand to usher your loved one into an era of prosperity and success.",
        type: "congratulation",
    },
    {
        productname: "Daniella Grand Opening Stand",
        image: "../Media/PRODUCTS/flower18.jpg",
        price: "2880000",
        quantity: 1,
        detail: "",
        type: "congratulation",
    },
    {
        productname: "Majestic",
        image: "../Media/PRODUCTS/flower19.webp",
        price: "2880000",
        quantity: 1,
        detail: "Starting a new venture is a bold step for anyone and this congratulations flower conveys your admiration for their new chapter in life.Majestic is designed with bold colours, from the choice of flowers and foliage all the way down to its luxurious wraps and ribbons.Send your congrats in style!",
        type: "congratulation",
    },
    {
        productname: "Jodie Phalaenopsis Orchid (2 stalks)",
        image: "../Media/PRODUCTS/flower20.webp",
        price: "880000",
        quantity: 1,
        detail: "Looking for an EXTRA special grand opening gift? Give something that they'll always remember, and that will always remind them of you. Like our stunning Jodie Phalaenopsis Orchid which will last for years to come with proper care!",
        type: "congratulation",
    },
    {
        productname: "S. Captivating",
        image: "../Media/PRODUCTS/flower21.webp",
        price: "750000",
        quantity: 1,
        detail: "A medley of cherry pink Matthiola, 2 tone purple Dendobrium, purple Mokara, green Dendobrium, maroon and lilac Ping Pong this curation will be the center of attention.",
        type: "congratulation",
    },
    {
        productname: "Skye Grand Opening Flower Stand",
        image: "../Media/PRODUCTS/flower22.jpg",
        price: "2880000",
        quantity: 1,
        detail: "The sky's the limit! Keep flying high! and Let your dreams take flight!.These are all the words and feelings that you'll convey with Skye. Featuring feathery blue foliage, sunset-toned blooms and a 3 rose-gold balloons, is there a better way to say it all?",
        type: "congratulation",
    },

    {
        productname: "Omakase Flower Stand",
        image: "../Media/PRODUCTS/flower23.webp",
        price: "1200000",
        quantity: 1,
        detail: "Send a Large Standing Bouquet for Grand Openings, Congratulations and more! Bring a touch of celebration to...",
        type: "congratulation",
    },
    {
        productname: "Sierra Grand Opening Flower Stand",
        image: "../Media/PRODUCTS/flower24.webp",
        price: "2880000",
        quantity: 1,
        detail: "Made with everyone's favourite baby's breath, Sierra features a large poofy cloud of multi-coloured blooms to celebrate everything from grand openings to new beginnings! The best part? They dry up beautifully while maintaining their shape and colour, meaning they'll stay just as grand for months to come!",
        type: "congratulation",
    },
    {
        productname: "BLUE AND WHITE FLORAL WREATH",
        image: "../Media/PRODUCTS/flower25.jpg",
        price: "2880000",
        quantity: 1,
        detail: "A blue and white floral wreath suitable for the passing of a lady or gentleman. Lovely white roses fused with blue field iris, white carnations, daisies and statice sourced from local independent growers in Melbourne. Each and every one of our wreaths are prepared daily to ensure the freshness of our products. Growers deliver in the early hours of the morning to allow us sufficient time to prepare all orders. When you order with The Funeral Flower Shop, you're always purchasing a quality product and service to match. This wreath can be delivered to church services and funeral homes. In the fields below, please specify as many details as possible. We will always contact the funeral home to confirm service times and dates.",
        type: "sadness",
    },
    {
        productname: "BRIGHT YELLOW AND BLUE WREATH",
        image: "../Media/PRODUCTS/flower26.jpg",
        price: "2230000",
        quantity: 1,
        detail: "A blue and yellow floral wreath suitable for the passing of a lady or gentleman. Lovely yellow roses fused with blue field iris, gerberas, daisies and statice sourced from local independent growers in Melbourne.",
        type: "sadness",
    },
    {
        productname: "MAGNOLIA WREATH IN BLUE AND WHITE",
        image: "../Media/PRODUCTS/flower27.jpg",
        price: "2200000",
        quantity: 1,
        detail: "A blue and white floral wreath including lovely Magnolia foliage for it's base. This wreath brings together a collection of fine seasonal flowers such as roses, gerberas, iris and stock flowers. The colours of this wreath make it suitable for delivery on the passing of a lady or gentleman. Blue being the colour of the sky and ocean is known to be a very calming colour. White is a peaceful and serene colour associated with sympathy occasions because of it's purity. This wreath can be delivered to church service or funeral homes. Please specify as many details below as possible. We will always contact the funeral home to confirm service times and dates.",
        type: "sadness",
    },
    {
        productname: "FLORAL TRIBUTE IN RED",
        image: "../Media/PRODUCTS/flower28.jpg",
        price: "2200000",
        quantity: 1,
        detail: "A visually stunning and vibrant red rose, gerbera, lily and mixed assorted floral wreath suitable for delivery to the funeral home or church service. Red is a royal colour associated with class and honour. This would make the perfect farewell tribute to a beloved friend, family member or colleague. With an assortment of flowers in red hues and displayed in a traditional symmetrically style offers a striking visual impact. Suitable for the passing of a lady or gentleman - and can only be delivered to a church service or funeral home. For flowers going to the family home or wake, please visit our sympathy flower catalog.",
        type: "sadness",
    },
    {
        productname: "PINK FLORAL WREATH FOR A LADY",
        image: "../Media/PRODUCTS/flower29.jpg",
        price: "2200000",
        quantity: 1,
        detail: "A bright pink and yellow assorted floral wreath suitable for the passing of a lady or young girl. Pink is a great choice for funeral flowers, since there are so many beautiful shades to work with and so many flowers available since it's such a common colour. Filled with luscious greenery and a variety of seasonal flowers, our wreaths are above and beyond what you'd expect from any florist. We are local to Melbourne and provide a service that most relay services cannot - it's an area we specialise in and aim to provide our customers with only the finest funeral wreaths.",
        type: "sadness",
    },
    {
        productname: "RED FLORAL TRIBUTE",
        image: "../Media/PRODUCTS/flower30.jpg",
        price: "2200000",
        quantity: 1,
        detail: "A lovely red and blue floral wreath including roses and iris and other seasonal flowers with red and blue hues. This wreath is not limited to the flowers you see in the photo, but may include other, flowers that will match the red and blue theme. The red and blue tones add a lovely contrasting touch to a wreath with a vibrant and exuberant display of colour. Suitable for the passing of a lady or gentleman and can be delivered next day across most Melbourne suburbs.",
        type: "sadness",
    },
    {
        productname: "SEASONAL WREATH IN PINK TONES",
        image: "../Media/PRODUCTS/flower31.jpg",
        price: "2200000",
        quantity: 1,
        detail: "A bright pink assorted floral wreath suitable for the passing of a female. This lovely wreath comes in assorted pink tones comprising of carnations and roses. Our wreaths are above and beyond what you'd expect from any florist. We are local to Melbourne and provide a service that one would expect at such an important time for the family.",
        type: "sadness",
    },
    {
        productname: "LILAC AND CREAM ROSES",
        image: "../Media/PRODUCTS/flower32.jpg",
        price: "2200000",
        quantity: 1,
        detail: "This Lilac, Cream and Pink rose wreath combines some lovely pastel hues suitable for the passing of a female. This wreath offers a memorable floral tribute for a beloved sister, friend, colleague, family member or relative. Our floral tributes are all custom made and require at least 24 hours to prepare. Please ensure you order early as same day delivery is not available.",
        type: "sadness",
    },
    {
        productname: "Based Funeral Wreath",
        image: "../Media/PRODUCTS/flower33.jpg",
        price: "2880000",
        quantity: 1,
        detail: "A lovely funeral wreath based in all white Chrysanthemums. A top spray of mixed seasonal flowers sits upon the Chrysanthemums just perfectly. ",
        type: "sadness",
    },
    {
        productname: "Heartfelt Sympathy Spray",
        image: "../Media/PRODUCTS/flower34.jpg",
        price: "1880000",
        quantity: 1,
        detail: "A peaceful display of your heartfelt sympathy, this pure white spray of hydrangea, roses and lilies brings a natural serenity to the service.",
        type: "sadness",
    },
    {
        productname: "Magnificent Life Spray",
        image: "../Media/PRODUCTS/flower35.jpg",
        price: "2280000",
        quantity: 1,
        detail: ".An elegant expression of sympathy, this wondrous white and green spray conveys purity and peace. A glorious choice for a magnificent memorial.",
        type: "sadness",
    },
    {
        productname: "Rainbow Of Remembrance Spray",
        image: "../Media/PRODUCTS/flower36.jpg",
        price: "2680000",
        quantity: 1,
        detail: "Your sincere wishes for peace and harmony resonate beautifully in this perfectly balanced arrangement of pink lilies, yellow gerberas and purple larkspur.",
        type: "sadness",
    },
    {
        productname: " Lavandula",
        image: "../Media/PRODUCTS/flower37.webp",
        price: "900000",
        quantity: 1,
        detail: "Lavandula arrangement features nature's best remedy for a good night's sleep. Place it in bedroom for natural scent of Lavender that lingers in your sleep",
        type: "display",
    },
    {
        productname: "Rose Money Flower Bouquet Gift for Her ",
        image: "../Media/PRODUCTS/flower38.jpg",
        price: "52000000",
        quantity: 1,
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
        type: "display",
    }, {
        productname: "Money Flower Bouquet Rosie  ",
        image: "../Media/PRODUCTS/flower39.jpg",
        price: "21000000",
        quantity: 1,
        detail: "traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything!",
        type: "display",
    }, {
        productname: "Money Flower Bouquet Gift for sunshine ",
        image: "../Media/PRODUCTS/flower40.jpg",
        price: "9500000",
        quantity: 1,
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
        type: "display",
    }, {
        productname: "Money Flower Bouquet Gift for us ",
        image: "../Media/PRODUCTS/flower41.jpg",
        price: "10800000",
        quantity: 1,
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
        type: "display",
    }, {
        productname: "Money Flower Bouquet Gift for sounds ",
        image: "../Media/PRODUCTS/flower42.jpg",
        price: "112000000",
        quantity: 1,
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
        type: "display",
    }, {
        productname: " Money Flower Bouquet Gift for rich",
        image: "../Media/PRODUCTS/flower43.jpg",
        price: "12200000",
        quantity: 1,
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
        type: "display",
    }, {
        productname: "Money Flower Bouquet Gift for heart ",
        image: "../Media/PRODUCTS/flower44.jpg",
        price: "25000000",
        quantity: 1,
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
        type: "display",
    }, {
        productname: "Money Flower Bouquet Gift for loving you ",
        image: "../Media/PRODUCTS/flower45.jpg",
        price: "11900000",
        quantity: 1,
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
        type: "display",
    }, {
        productname: " Notthing gonna change my love for you",
        image: "../Media/PRODUCTS/flower46.jpg",
        price: "108000000",
        quantity: 1,
        detail: "",
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
    }, {
        productname: "Me before you ",
        image: "../Media/PRODUCTS/flower47.jpg",
        price: "34500000",
        quantity: 1,
        detail: "",
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
    }, {
        productname: "youre my life ",
        image: "../Media/PRODUCTS/flower48.jpg",
        price: "100000000",
        quantity: 1,
        detail: "Skip traditional rose bouquets and order our Rose Money Flower Bouquet made to impress! The perfect gift for those who has everything! ",
        type: "display",
    }, {
        productname: "Lucky Clover Plant",
        image: "../Media/PRODUCTS/flower49.webp",
        price: "400000",
        quantity: 1,
        detail: "Also called Iron Cross Plant, Good Luck Plant and Shamrock Plant, the Lucky Clover Plant is considered by some people to be bearers or representation of good luck because of their clover-like leaves. ",
        type: "plant",
    }, {
        productname: "Dawn Redwood Bonsai - Metasequoia Glyptostroboides (Japan) ",
        image: "../Media/PRODUCTS/flower50.webp",
        price: "900000",
        quantity: 1,
        detail: "The Dawn Redwood bonsai, derived from the Metasequoia glyptostroboides tree, is a captivating addition to any bonsai collection.",
        type: "plant",
    }, {
        productname: "Large Money Tree ",
        image: "../Media/PRODUCTS/flower51.webp",
        price: "2300000",
        quantity: 1,
        detail: "Pachira aquatica is a very popular houseplant that’s commonly called Money Tree.",
        type: "plant",
    }, {
        productname: "Artificial Silk Phalaenopsis in Gold Pot",
        image: "../Media/PRODUCTS/flower52.webp",
        price: "1900000",
        quantity: 1,
        detail: "Introducing our exquisite Phalaenopsis Silk Flower in a Gold Pot, a stunning decorative piece that brings the allure of orchids into your living space.",
        type: "plant",
    }, {
        productname: "SEDUM DONKEY'S TAIL SUCCULENT ",
        image: "../Media/PRODUCTS/flower53.webp",
        price: "100000",
        quantity: 1,
        detail: "Sedum Burrito/ Sedum Morganianum, also known as Burro's Tail or Donkey's Tail Succulent, is native to Mexico. It is an easy-to-grow perennial succulent and can tolerate any types of soil with good drainage. ",
        type: "plant",
    }, {
        productname: "MOONSTONES PACHYPHYTUM ",
        image: "../Media/PRODUCTS/flower54.webp",
        price: "160000",
        quantity: 1,
        detail: "",
        type: "plant",
    }
]
// function tạo id
function createId() {
    return Math.floor(Math.random() * 9999999999999 + new Date().getMilliseconds())
}
for (let i = 0; i < products.length; i++) {
    products[i].id = createId();
}
console.log(products);
// localStorage.setItem("products", JSON.stringify(products)); 